services:
  postgresql:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: logs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
