create table study_group
(
    id     bigint generated by default as identity primary key,
    number int not null,
    course int not null
);

create table student
(
    id        uuid default gen_random_uuid() primary key,
    id_number bigint not null unique,
    email     text   not null unique,
    full_name text   not null,
    group_id  bigint not null,

    foreign key (group_id) references study_group (id) on delete cascade
);
comment on column student.id_number is 'номер студенческого билета';